Better handle GitHub bad token
gitextensions/Git.hub pull request #15
Opened 2020-04-27 23:38 UTC by pmiossec

Transform a NRE in an UnauthorizedAccessException with clearer message

First step to handle https://github.com/gitextensions/gitextensions/issues/7641

2020-04-27 23:39 UTC, pmiossec commented
Just review the first commit.

2020-04-28 09:16 UTC, RussKie requested changes

2020-04-28 09:16 UTC, RussKie commented on Git.hub/Client.cs
> +        private T DoRequest<T>(IRestRequest request, bool shouldNotFail = false) where T : new()
Please invert `shouldNotFail`. It leads to a mental overload when staring at `true` to understand what it means.
```suggestion
        private T DoRequest<T>(IRestRequest request, bool throwOnError = true) where T : new()
```

2020-04-28 09:17 UTC, RussKie commented on Git.hub/Client.cs
> +        private T DoRequest<T>(RestRequest request, bool shouldNotFail = false) where T : new()
Please move the private method after publics.

2020-04-28 09:27 UTC, gerhardol approved these changes
OK for me

2020-04-28 09:27 UTC, gerhardol commented on Git.hub/Client.cs
> +            if (repos?.Repositories == null)
Maybe add {} to conform with GE style (but will not be the same as other files in this submodule)

2020-04-28 20:51 UTC, pmiossec commented
Updated.

2020-04-28 21:58 UTC, RussKie approved these changes

2020-04-29 07:12 UTC, gerhardol approved these changes

2020-05-03 12:39 UTC, merged